# Boiler plate

```{r}
# Library
library(ggplot2)
library(reshape2)
library(ggnewscale)
library(ggtext)
```

And also set the order of the samples, so the wild samples and the zoo stuff are grouped together

```{r}
sample_order <- c("1_S1","10_S5","2_S2","6_S3","87_S105","9_S4", #Wild
                        "33_S25","24_S16","25_S17","44_S36","32_S24", #ZMT7
                        "37_S29","23_S15","42_S34","36_S28", #ZMT6
                        "19_S12","17_S10","22_S14","18_S11","21_S13", #ZMT5
                        "35_S27","26_S18","27_S19","40_S32","34_S26", #ZMT4
                        "31_S23","28_S20","29_S21","41_S33","30_S22", #ZMT3
                        "48_S40","43_S35","15_S8","14_S7","39_S31","47_S39",
                        "12_S77", #ZMT2
                        "49_S41","45_S37","16_S9","38_S30","46_S38","11_S6",
                        #ZMT1^
                        "89_S78", #Sire
                        "90_S79","91_S80","92_S81","93_S82","94_S83","95_S84",
                        "96_S85","97_S86", #MaTD 
                        "98_S87","99_S88","100_S89","101_S90","102_S91","103_S92",
                        "104_S93","105_S94","106_S95","107_S96","108_S97",
                        "109_S98","110_S99","111_S100","112_S101","113_S102",
                        "114_S103","115_S104", #MaTC 
                        "83_S74","84_S75","80_S71","81_S72","82_S73", #LTD
                        "78_S69","54_S46","64_S56","69_S61","71_S63","65_S57",
                        "51_S43","58_S50","73_S65","72_S64","57_S49","76_S67",
                        "62_S54","63_S55","52_S44","53_S45","61_S53","68_S60",
                        "77_S68","70_S62","50_S42","66_S58","60_S52","55_S47",
                        "67_S59","59_S51","74_S66","56_S48")

sample_order_ID <- c("WMT1_0","WMT2_0","WMT3_0","WMT4_0","WMT5_0",
                     "WMT6_0", # Wild
                     "ZMT7_0","ZMT7_1","ZMT7_2","ZMT7_3","ZMT7_4", # Zoo1
                     "ZMT6_0","ZMT6_1","ZMT6_2","ZMT6_3",
                     "ZMT5_0","ZMT5_1","ZMT5_2","ZMT5_3","ZMT5_4",
                     "ZMT4_0","ZMT4_1","ZMT4_2","ZMT4_3","ZMT4_4",
                     "ZMT3_0","ZMT3_1","ZMT3_2","ZMT3_3","ZMT3_4",
                     "ZMT2_0","ZMT2_1","ZMT2_2","ZMT2_3","ZMT2_4","ZMT2_5",
                     "ZMT2_6", # Zoo2
                     "ZMT1_0","ZMT1_1","ZMT1_2","ZMT1_3",
                     "ZMT1_4","ZMT1_5", 
                     "MaTS_0",
                     "MaTD_0","MaTD_1","MaTD_2","MaTD_3","MaTD_4","MaTD_5","MaTD_6",
                     "MaTD_7", #Zoo3
                     "MaTC_0","MaTC_1","MaTC_2","MaTC_3","MaTC_4","MaTC_5",
                     "MaTC_6","MaTC_7","MaTC_8","MaTC_9","MaTC_10","MaTC_11",
                     "MaTC_12","MaTC_13","MaTC_14","MaTC_15","MaTC_16",
                     "MaTC_17",
                     "LTD_0","LTD_1","LTD_2","LTD_3","LTD_4", # Zoo4
                     "LTC_0","LTC_1","LTC_2","LTC_3","LTC_4",
                     "LTC_5","LTC_6","LTC_7","LTC_8","LTC_9",
                     "LTC_10","LTC_11","LTC_12","LTC_13","LTC_14",
                     "LTC_15","LTC_16","LTC_17","LTC_18","LTC_19",
                     "LTC_20","LTC_21","LTC_22","LTC_23","LTC_24",
                     "LTC_25","LTC_26","LTC_27")

sample_order_animal <- c("WMT1","WMT2","WMT3","WMT4","WMT5",
                     "WMT6", # Wild
                     "ZMT1",
                     "ZMT2",
                     "ZMT3",
                     "ZMT4",
                     "ZMT5",
                     "ZMT6",
                     "ZMT7", 
                     "MaTS",
                     "MaTD",
                     "MaTC",
                     "LTD",
                     "LTC")
```

# Get the data

```{r}
# Get antimicrobial resistance genes
data_ARG <- read.delim(file = "../Data/CombinedTableAllARGs_by_gene.txt", 
                       sep = "\t", 
                       header = TRUE,
                       check.names = FALSE) %>% 
  select(-"88_S106", -"86_S76") 

# Grab the Gene names

data_disin <- read.delim(file = "../Data/CombinedTableAllARGs_disinfectant_FirstRun.txt", 
                         sep = "\t", 
                         header = TRUE,
                         check.names = FALSE) %>% 
  select(-"88_S106", -"86_S76")
```

# Plot the heat map for wild v. *ex-situ*

```{r}
# Factor Wild and ex-situ so that everything in the plots order correctly
meta_test <- metadata_mt_select %>% 
  mutate(Specific_Group = factor(.$Specific_Group, levels = c("Wild", "Ex-situ"))) %>% 
  select(Fastq_name, Animal_Code, Specific_Group)


data_plot <- data_ARG %>% 
  select(X,any_of(meta_test$Fastq_name)) %>% 
  column_to_rownames(var = "X") %>% 
  filter(rowSums(across()) > 0) %>% # Remove Accessions that weren't identified anywhere
  mutate(across(where(is.numeric), # Convert Identity to Presence/Absence
                ~ifelse(.x > 0, "Present","Absent"))) %>% 
  t() %>% as.data.frame() %>% 
  rownames_to_column(var = "Fastq_name") %>%
  left_join(., meta_test, by = "Fastq_name") %>% 
  select(-Fastq_name, -Specific_Group) %>% 
  column_to_rownames(var = "Animal_Code") %>% 
  t() %>% as.data.frame() %>% 
  rownames_to_column(var = "X")

# Make it a graphable variable
data_plot$lineage <- as.factor(data_plot$X)
data_plot <- melt(data_plot[,2:ncol(data_plot)], id.vars = "lineage") %>% 
  mutate(variable = factor(variable, levels = sample_order_animal))

# Need extra variable to get the color bars into my ggplot
group_bar <- meta_test %>%
  mutate(Animal_Code = factor(Animal_Code, levels = sample_order_animal)) %>%
  mutate(lineage = rep(0, 13)) %>% 
  select(-Fastq_name)

# Plot
ggplot(data = data_plot, aes(x = variable, y = lineage, fill = value)) +
  geom_tile() +
  scale_fill_manual(
    name = "ARG is:",
    values = c("blue4", "orange1"),  # for the tile fill
    guide = guide_legend(order = 1) # So the legend orders correctly
  ) +
  new_scale_fill() + # ---- reset fill scale here ----
  geom_tile(
    data = group_bar,
    aes(x = Animal_Code, y = lineage, fill = Specific_Group),
    height = 0.9,
    inherit.aes = FALSE
  ) +
  scale_fill_manual(
    name = "Group:",
    values = c(
      "Wild"    = "#99FF33",
      "Ex-situ" = "#A6A6A6"
    ),
    labels = c(
      "Wild" =  expression(italic("In-situ")),
      "Ex-situ" = expression(italic("Ex-situ"))
    ),
    guide = guide_legend(order = 2) # So the legend orders correctly
  ) +
  xlab("Animal") + ylab("Antibiotic Resistance Gene") + 
  ggtitle("*In-situ* v. *ex-situ* mt. tapirs ARG presence/absence") + 
  theme(axis.text.x = element_text(angle = 90), 
        plot.title = element_markdown())

# Save the image
ggsave(file = "../Images/ARG_WvE.pdf",
       width=6,
       height=3.6)
ggsave(file = "../Images/ARG_WvE.svg",
       width=6,
       height=3.6)
ggsave(file = "../Images/ARG_WvE.png",
       width=6,
       height=3.6)
```

# ZMT1 across time

```{r}
# Select the samples
meta_test <- metadata %>% 
  filter(Animal_Code %in% c("ZMT1")) 
# Remove Accessions where the columns sum to 0
data_plot <- data_ARG %>% 
  select(X,any_of(meta_test$Fastq_name)) %>% 
  column_to_rownames(var = "X") %>% 
  filter(rowSums(across()) > 0) %>%
  rownames_to_column(var = "X")
# Make it a graphable variable
data_plot$lineage <- as.factor(data_plot$X)
data_plot <- melt(data_plot[,2:ncol(data_plot)], id.vars = "lineage") %>% 
  mutate(variable = factor(variable, levels = sample_order))


# Make plot
ggplot(data = data_plot, 
       aes(x = variable, 
           y = lineage, 
           fill = value)) + 
  geom_tile() +
  scale_fill_gradient(low="blue4", high="orange1", name = "% Identity") + 
  theme(
    axis.text.x = element_text(angle = 90)
  ) + 
  xlab("Sample") + 
  ylab("Antimicrobial Resistance Gene") + 
  ggtitle("ZMT1 ARG presence/absence across time")
```

# ZMT2 across time

```{r}
# Select the samples
meta_test <- metadata %>% 
  filter(Animal_Code %in% c("ZMT2")) 
# Remove Accessions where the columns sum to 0
data_plot <- data_ARG %>% 
  select(X,any_of(meta_test$Fastq_name)) %>% 
  column_to_rownames(var = "X") %>% 
  filter(rowSums(across()) > 0) %>%
  mutate(across(where(is.numeric),
                ~ifelse(.x > 0, "Present","Absent"))) %>% # Convert the Identity to Presence/Absence
  t() %>% as.data.frame() %>% 
  rownames_to_column(var = "remove") %>% 
  mutate(new_names = meta_test$Sample_ID) %>% 
  select(-remove) %>% 
  column_to_rownames(var = "new_names") %>% 
  t() %>% as.data.frame() %>% 
  rownames_to_column(var = "X")
# Make it a graphable variable
data_plot$lineage <- as.factor(data_plot$X)
data_plot <- melt(data_plot[,2:ncol(data_plot)], id.vars = "lineage") %>% 
  mutate(variable = factor(variable, levels = sample_order_ID))


# Plot
ggplot(data = data_plot, aes(x = variable, y = lineage, fill = value)) +
  geom_tile() +
  scale_fill_manual(
    name = "ARG is:",
    values = c("blue4", "orange1")  # for the tile fill
  ) +
  xlab("Sample") + ylab("Antibiotic Resistance Gene") + 
  ggtitle("ZMT2 ARG presence/absence across time") + 
  theme(axis.text.x = element_text(angle = 90), 
        plot.title = element_markdown())
# Save the image
# ggsave(file = "../Images/ARG_ZMT2.pdf", 
#        width=6, 
#        height=4.7)
# ggsave(file = "../Images/ARG_ZMT2.svg", 
#        width=6, 
#        height=4.7)
# ggsave(file = "../Images/ARG_ZMT2.png", 
#        width=6, 
#        height=4.7)

# Make plot
ggplot(data = data_plot, 
       aes(x = variable, 
           y = lineage, 
           fill = value)) + 
  geom_tile() +
  scale_fill_gradient(low="blue4", high="orange1", name = "% Identity") + 
  theme(
    axis.text.x = element_text(angle = 90)
  ) + 
  xlab("Sample ID (Ordered by first to last sample taken)") + 
  ylab("Antibiotic Resistance Gene") + 
  ggtitle("ZMT2 ARG presence/absence across time")
```

# ZMT3 across time

```{r}
# Select the samples
meta_test <- metadata %>% 
  filter(Animal_Code %in% c("ZMT3")) 
# Remove Accessions where the columns sum to 0
data_plot <- data_ARG %>% 
  select(X,any_of(meta_test$Fastq_name)) %>% 
  column_to_rownames(var = "X") %>% 
  filter(rowSums(across()) > 0) %>%
  mutate(across(where(is.numeric),
                ~ifelse(.x > 0, "Present","Absent"))) %>% # Convert the Identity to Presence/Absence
  t() %>% as.data.frame() %>% 
  rownames_to_column(var = "Fastq_name") %>% 
  left_join(., meta_test[,1:3], by = "Fastq_name") %>% 
  select(-Fastq_name, -Animal_Code) %>% 
  column_to_rownames(var = "Sample_ID") %>% 
  t() %>% as.data.frame() %>% 
  rownames_to_column(var = "X")
# Make it a graphable variable
data_plot$lineage <- as.factor(data_plot$X)
data_plot <- melt(data_plot[,2:ncol(data_plot)], id.vars = "lineage") %>% 
  mutate(variable = factor(variable, levels = sample_order_ID))


# Plot
ggplot(data = data_plot, aes(x = variable, y = lineage, fill = value)) +
  geom_tile() +
  scale_fill_manual(
    name = "ARG is:",
    values = c("blue4", "orange1")  # for the tile fill
  ) +
  xlab("Sample") + ylab("Antibiotic Resistance Gene") + 
  ggtitle("ZMT3 ARG presence/absence across time") + 
  theme(axis.text.x = element_text(angle = 90), 
        plot.title = element_markdown())


# # Make plot
# ggplot(data = data_plot, 
#        aes(x = variable, 
#            y = lineage, 
#            fill = value)) + 
#   geom_tile() +
#   scale_fill_gradient(low="blue4", high="orange1", name = "% Identity") + 
#   theme(
#     axis.text.x = element_text(angle = 90)
#   ) + 
#   xlab("Sample") + 
#   ylab("ARG Accession Number") + 
#   ggtitle("ZMT3 ARG presence absence")
```

# ZMT4 across time

```{r}
# Select the samples
meta_test <- metadata %>% 
  filter(Animal_Code %in% c("ZMT4")) 
# Remove Accessions where the columns sum to 0
data_plot <- data_ARG %>% 
  select(X,any_of(meta_test$Fastq_name)) %>% 
  column_to_rownames(var = "X") %>% 
  filter(rowSums(across()) > 0) %>%
  rownames_to_column(var = "X")
# Make it a graphable variable
data_plot$lineage <- as.factor(data_plot$X)
data_plot <- melt(data_plot[,2:ncol(data_plot)], id.vars = "lineage") %>% 
  mutate(variable = factor(variable, levels = sample_order))


# Make plot
ggplot(data = data_plot, 
       aes(x = variable, 
           y = lineage, 
           fill = value)) + 
  geom_tile() +
  scale_fill_gradient(low="blue4", high="orange1", name = "% Identity") + 
  theme(
    axis.text.x = element_text(angle = 90)
  ) + 
  xlab("Sample") + 
  ylab("ARG Accession Number") + 
  ggtitle("ZMT4 ARG presence/absence")
```

# ZMT5 across time

```{r}
# Select the samples
meta_test <- metadata %>% 
  filter(Animal_Code %in% c("ZMT5")) 
# Remove Accessions where the columns sum to 0
data_plot <- data_ARG %>% 
  select(X,any_of(meta_test$Fastq_name)) %>% 
  column_to_rownames(var = "X") %>% 
  filter(rowSums(across()) > 0) %>%
  rownames_to_column(var = "X")
# Make it a graphable variable
data_plot$lineage <- as.factor(data_plot$X)
data_plot <- melt(data_plot[,2:ncol(data_plot)], id.vars = "lineage") %>% 
  mutate(variable = factor(variable, levels = sample_order))


# Make plot
ggplot(data = data_plot, 
       aes(x = variable, 
           y = lineage, 
           fill = value)) + 
  geom_tile() +
  scale_fill_gradient(low="blue4", high="orange1", name = "% Identity") + 
  theme(
    axis.text.x = element_text(angle = 90)
  ) + 
  xlab("Sample") + 
  ylab("ARG Accession Number") + 
  ggtitle("ZMT5 ARG presence/absence")
```

# ZMT6 across time

```{r}
# Select the samples
meta_test <- metadata %>% 
  filter(Animal_Code %in% c("ZMT6")) 
# Remove Accessions where the columns sum to 0
data_plot <- data_ARG %>% 
  select(X,any_of(meta_test$Fastq_name)) %>% 
  column_to_rownames(var = "X") %>% 
  filter(rowSums(across()) > 0) %>%
  rownames_to_column(var = "X")
# Make it a graphable variable
data_plot$lineage <- as.factor(data_plot$X)
data_plot <- melt(data_plot[,2:ncol(data_plot)], id.vars = "lineage") %>% 
  mutate(variable = factor(variable, levels = sample_order))


# Make plot
ggplot(data = data_plot, 
       aes(x = variable, 
           y = lineage, 
           fill = value)) + 
  geom_tile() +
  scale_fill_gradient(low="blue4", high="orange1", name = "% Identity") + 
  theme(
    axis.text.x = element_text(angle = 90)
  ) + 
  xlab("Sample") + 
  ylab("ARG Accession Number") + 
  ggtitle("ZMT6 ARG presence/absence")
```

# ZMT7 across time

```{r}
# Select the samples
meta_test <- metadata %>% 
  filter(Animal_Code %in% c("ZMT7")) 
# Remove Accessions where the columns sum to 0
data_plot <- data_ARG %>% 
  select(X,any_of(meta_test$Fastq_name)) %>% 
  column_to_rownames(var = "X") %>% 
  filter(rowSums(across()) > 0) %>%
  rownames_to_column(var = "X")
# Make it a graphable variable
data_plot$lineage <- as.factor(data_plot$X)
data_plot <- melt(data_plot[,2:ncol(data_plot)], id.vars = "lineage") %>% 
  mutate(variable = factor(variable, levels = sample_order))


# Make plot
ggplot(data = data_plot, 
       aes(x = variable, 
           y = lineage, 
           fill = value)) + 
  geom_tile() +
  scale_fill_gradient(low="blue4", high="orange1", name = "% Identity") + 
  theme(
    axis.text.x = element_text(angle = 90)
  ) + 
  xlab("Sample") + 
  ylab("ARG Accession Number") + 
  ggtitle("ZMT7 ARG presence/absence")
```

# Wild and ex-situ disinfectant

```{r}
# Select the samples
meta_test <- metadata %>% 
  filter(Specific_Group %in% c("Wild","Ex-situ")) %>% 
  group_by(Animal_Code) %>% 
  arrange(Date_collected, .by_group = TRUE) %>% 
  slice(1) %>% 
  ungroup() %>% 
  mutate(Specific_Group = factor(.$Specific_Group, levels = c("Wild", "Ex-situ")))
# Remove Accessions where the columns sum to 0
data_plot <- data_disin %>% 
  select(X,any_of(meta_test$Fastq_name)) %>% 
  column_to_rownames(var = "X") %>% 
  filter(rowSums(across()) > 0) %>%
  rownames_to_column(var = "X")
# Make it a graphable variable
data_plot$lineage <- as.factor(data_plot$X)
data_plot <- melt(data_plot[,2:ncol(data_plot)], id.vars = "lineage") %>% 
  mutate(variable = factor(variable, levels = sample_order))


# Make plot
ggplot(data = data_plot, 
       aes(x = variable, 
           y = lineage, 
           fill = value)) + 
  geom_tile() +
  scale_fill_gradient(low="blue4", high="orange1", name = "% Identity") + 
  theme(
    axis.text.x = element_text(angle = 90)
  ) + 
  xlab("Sample") + 
  ylab("Disinfectant Resistance Gene Accession Number")
```

# Plot the heat map for Malayan Calf

```{r}
# Select the samples
meta_test <- metadata %>% 
  filter(Tapir %in% c("Malayan")) %>% 
  filter(Specific_Group %in% c("Calf")) 
# Remove Accessions where the columns sum to 0
data_plot <- data_ARG %>% 
  select(X,any_of(meta_test$Fastq_name)) %>% 
  column_to_rownames(var = "X") %>% 
  filter(rowSums(across()) > 0) %>%
  rownames_to_column(var = "X")
# Make it a graphable variable
data_plot$lineage <- as.factor(data_plot$X)
data_plot <- melt(data_plot[,2:ncol(data_plot)], id.vars = "lineage") %>% 
  mutate(variable = factor(variable, levels = sample_order))


# Make plot
ggplot(data = data_plot, 
       aes(x = variable, 
           y = lineage, 
           fill = value)) + 
  geom_tile() +
  scale_fill_gradient(low="blue4", high="orange1", name = "% Identity") + 
  theme(
    axis.text.x = element_text(angle = 90)
  ) + 
  xlab("Sample") + 
  ylab("Antimicrobial Resistance Gene") + 
  ggtitle("Malayan Calf ARG presence/absense across time")
  
```

# Plot the Lowland calf

```{r}
# Select the samples
meta_test <- metadata %>% 
  filter(Tapir %in% c("Lowland")) %>% 
  filter(Specific_Group %in% c("Calf")) 
# Remove Accessions where the columns sum to 0
data_plot <- data_ARG %>% 
  select(X,any_of(meta_test$Fastq_name)) %>% 
  column_to_rownames(var = "X") %>% 
  filter(rowSums(across()) > 0) %>%
  rownames_to_column(var = "X")
# Make it a graphable variable
data_plot$lineage <- as.factor(data_plot$X)
data_plot <- melt(data_plot[,2:ncol(data_plot)], id.vars = "lineage") %>% 
  mutate(variable = factor(variable, levels = sample_order))


# Make plot
ggplot(data = data_plot, 
       aes(x = variable, 
           y = lineage, 
           fill = value)) + 
  geom_tile() +
  scale_fill_gradient(low="blue4", high="orange1", name = "% Identity") + 
  theme(
    axis.text.x = element_text(angle = 90)
  ) + 
  xlab("Sample") + 
  ylab("Antimicrobial Resistance Gene") +
  ggtitle("Lowland Calf ARG presence/absense across time")
```
