# Boiler Plate

```{r}
library(Maaslin2)
library(vroom)
library(ggrepel)
library(ggtext)
```

# Function

```{r}
# Graph and save volcano plot
volcano_plot <- function(maaslin_file, output_path, output_name, cutoff = 0.05, Plot_title = "Wild v. *ex-situ*", chosen = c()) {
  
  # Load the data
  taxa <- vroom(maaslin_file, altrep = FALSE)
  
  taxa$symbol=taxa$feature # We want the feature names to be the labels.
  
  sigUp <- which(taxa$coef>0 & taxa$qval<cutoff) # right top quad
  sigDown <- which(taxa$coef<0 & taxa$qval<cutoff) # left top quad
  nonSigUp <- which(taxa$coef>0 & taxa$qval>cutoff) # right bottom quad
  nonSigDown <- which(taxa$coef<0 & taxa$qval>cutoff) # left bottom quad
  
  taxa$Significance <- "FDR<1e-2, Increased Abundance"
  taxa[ sigUp, "Significance"] <- "FDR<0.05, Increased Abundance"
  taxa[ sigDown, "Significance"] <- "FDR<0.05, Decreased Abundance"
  taxa[ nonSigUp, "Significance"] <- "Less Significant, Increased Abundance"
  taxa[ nonSigDown, "Significance"] <- "Less Significant, Decreased Abundance"
  
  
  # Make the volcano plot ------------------------------------------------------
  
  #pdf(file=paste(output_path, paste(output_name, "pdf", sep = "."), sep = "/"), height = 24, width = 24) # Open the pdf
  
  ggplot(taxa, aes(x = coef, y = -log10(qval))) +
    geom_point(aes(fill = Significance, shape = Significance, color = Significance), size = 1.75) +
    geom_hline(yintercept = -log10(0.05), color = "darkred", linetype = "dashed") + 
    scale_fill_manual(values = c("#99FF33", "#A6A6A6", "#B6EC80", "#D1D1D1")) + # "#6FDE00", "#A6A6A6"
    scale_color_manual(values = c("black", "black", "#B6EC80", "#D1D1D1")) + # #696969
    scale_shape_manual(values = c(21,21,19,19)) + 
    xlab("Effect size") +
    ylab(expression('-Log'[10]*'P-Value')) +
    ggtitle(Plot_title) +
    theme_bw() + 
    theme(text = element_text(size = 20),
          legend.position = "right", 
          legend.text = element_text(size = 15),
          legend.title = element_text(size = 15),
          legend.key.height=unit(2, "cm"),
          plot.title= element_markdown(),
          # panel.background = element_rect(fill = "black")
    ) +
    geom_text_repel(
      data = subset(taxa, feature %in% chosen), # qval < cutoff), # Select the dots that get labels
      aes(label = symbol),
      size = 5,
      box.padding = unit(0.4, "lines"),
      point.padding = unit(0.3, "lines"),
      max.overlaps = 25,
      force = 25,   # pushes labels away from each other
      force_pull = 1, # pull labels toward points
      min.segment.length = 0  # ensures a segment is always drawn
    )
  
  
  #dev.off() # Close the pdf
  
  # # Figure PDF
  # ggsave(paste(output_path, 
  #              paste(output_name, "Figure.pdf", sep = "_"), 
  #              sep = "/"), 
  #        width = 14, 
  #        height = 7)
  # 
  # # Figure SVG
  # ggsave(paste(output_path, 
  #              paste(output_name, "svg", sep = "."), 
  #              sep = "/"), 
  #        width = 14, 
  #        height = 7)
  # 
  #   # Figure SVG
  # ggsave(paste(output_path, 
  #              paste(output_name, "png", sep = "."), 
  #              sep = "/"), 
  #        width = 14, 
  #        height = 7)
  
  return(last_plot())
}
```

# Wild v. Ex-situ test

## For Bacteria

```{r}
Maaslin2(abund_bac_mt_select, 
         metadata_mt_select, 
         '../Data/Maaslin2_outs_rare/No rare select/Bacteria', # output location
         min_abundance = 0,
         min_prevalence = 0.1,
         max_significance = 0.05, #qval threshold for significance
         analysis_method = 'LM',
         correction = "BH",
         fixed_effects = c("Group"),
         standardize = FALSE, #z-scores for continuous metadata, none of the metadata in the study is continuous
         transform = 'LOG',
         normalization = 'TSS', 
         reference = c('Group,Wild'))
```

### Make and save the volcano plots

```{r}
volcano_plot("../Data/Maaslin2_outs_rare/No rare select/Bacteria/all_results.tsv", 
             "../Data/Maaslin2_outs_rare/No rare select/Bacteria",
             "Bacteria_only", Plot_title = "Wild v. *ex-situ* (Bacteria)",
             chosen = c("Vibrio.parahaemolyticus","Salmonella.bongori","Shigella.flexneri", 
                        "Escherichia.coli", "Veillonella.dispar","Fibrobacter.succinogenes",
                        "Corynebacterium.kefirresidentii",
                        "Treponema.bryantii","Treponema.ruminis","Ruminococcus.albus",
                        "Fibrobacter.succinogenes","Ruminococcus.champanellensis",
                        "Pseudomonas.sp..Nvir","Acetoanaerobium.sticklandii"))

# For presentation
volcano_plot("../Data/Maaslin2_outs_rare/No rare select/Bacteria/all_results.tsv", 
             "../Images/Marcos",
             "Volc_Bacteria", Plot_title = "Wild v. *ex-situ* (Bacteria)",
             chosen = c("Vibrio.parahaemolyticus","Shigella.flexneri", 
                        "Escherichia.coli","Fibrobacter.succinogenes",
                        "Corynebacterium.kefirresidentii",
                        "Treponema.bryantii","Treponema.ruminis","Ruminococcus.albus",
                        "Fibrobacter.succinogenes","Ruminococcus.champanellensis",
                        "Nitratifractor.salsuginis", "Paralysiella.testudinis"))
```

## For Archaea

```{r}
Maaslin2(abund_arch_mt_select, 
         metadata_mt_select, 
         '../Data/Maaslin2_outs_rare/No rare select/Archaea', # output location
         min_abundance = 0,
         min_prevalence = 0.1,
         max_significance = 0.05, #qval threshold for significance
         analysis_method = 'LM',
         correction = "BH",
         fixed_effects = c("Group"),
         standardize = FALSE, #z-scores for continuous metadata, none of the metadata in the study is continuous
         transform = 'LOG',
         normalization = 'TSS', 
         reference = c('Group,Wild'))
```

### Make and save the volcano plots

```{r}
volcano_plot("../Data/Maaslin2_outs_rare/No rare select/Archaea/all_results.tsv",
             "../Data/Maaslin2_outs_rare/No rare select/MountainWvC/Archaea",
             "Archaea_only", Plot_title = "Wild v. *ex-situ* (Archaea)",
             chosen = c("Methanoculleus.bourgensis","Methanofollis.aquaemaris","Methanofollis.liminatans",
                        "Methanolobus.zinderi","Methanoregula.boonei",
                        "Methanosarcina.acetivorans","Methanosarcina.siciliae",
                        "Methanospirillum.lacunae","Methanospirillum.stamsii","Methanobrevibacter.acididurans",
                        "Methanobrevibacter.smithii","Methanobrevibacter.intestini",
                        "Methanobrevibacter.millerae",
                        "Methanobrevibacter.olleyae","Methanobrevibacter.ruminantium",
                        "Methanobrevibacter.sp..TLL.48.HuF1"))
# "Methanosarcina.sp..WH1", "Methanobrevibacter.sp..AbM4", "Methanobrevibacter.sp..YE315", "Methanolobus.sp..WCC4"

# For presentation
volcano_plot("../Data/Maaslin2_outs_rare/No rare select/Archaea/all_results.tsv",
             "../Images/Marcos",
             "Volc_Archaea", Plot_title = "Wild v. *ex-situ* (Archaea)",
             chosen = c("Methanogenium.sp..S4BF","Methanoculleus.bourgensis",
                        "Methanobrevibacter.smithii","Methanobrevibacter.intestini",
                        "Methanobrevibacter.olleyae","Methanobrevibacter.ruminantium",
                        "Methanobrevibacter.sp..TLL.48.HuF1","Methanobrevibacter.sp..AbM4"))

```

## For Fungi

```{r}
Maaslin2(abund_fun_mt_select, 
         metadata_mt_select, 
         '../Data/Maaslin2_outs_rare/No rare select/Fungi', # output location
         min_abundance = 0,
         min_prevalence = 0.1,
         max_significance = 0.05, #qval threshold for significance
         analysis_method = 'LM',
         correction = "BH",
         fixed_effects = c("Group"),
         standardize = FALSE, #z-scores for continuous metadata, none of the metadata in the study is continuous
         transform = 'LOG',
         normalization = 'TSS', 
         reference = c('Group,Wild'))
```

### Make and save the volcano plots

```{r}
volcano_plot("../Data/Maaslin2_outs_rare/No rare select/Fungi/all_results.tsv", 
             "../Data/Maaslin2_outs_rare/No rare select/Fungi",
             "Fungi_only")
```

## For Virus

```{r}
Maaslin2(abund_virus_mt_select, 
         metadata_mt_select, 
         '../Data/Maaslin2_outs_rare/No rare select/Viruses', # output location
         min_abundance = 0,
         min_prevalence = 0.25,
         max_significance = 0.05, #qval threshold for significance
         analysis_method = 'LM',
         correction = "BH",
         fixed_effects = c("Group"),
         standardize = FALSE, #z-scores for continuous metadata, none of the metadata in the study is continuous
         transform = 'LOG',
         normalization = 'TSS', 
         reference = c('Group,Wild'))
```

### Make and save the volcano plots

```{r}
volcano_plot("../Data/Maaslin2_outs_rare/No rare select/Viruses/all_results.tsv", 
             "../Data/Maaslin2_outs_rare/No rare select/Viruses",
             "Viruses_only", chosen = c("Kratosvirus.quantuckense","Brigitvirus.brigit","Eponavirus.epona"))
```

## For plants

```{r}
Maaslin2(abund_plant_mt_select, 
         metadata_mt_select, 
         '../Data/Maaslin2_outs_rare/No rare select/Plants', # output location
         min_abundance = 0,
         min_prevalence = 0.1,
         max_significance = 0.05, #qval threshold for significance
         analysis_method = 'LM',
         correction = "BH",
         fixed_effects = c("Group"),
         standardize = FALSE, #z-scores for continuous metadata, none of the metadata in the study is continuous
         transform = 'LOG',
         normalization = 'TSS', 
         reference = c('Group,Wild'))
```

### Make and save the volcano plots

```{r}
volcano_plot("../Data/Maaslin2_outs_rare/No rare select/Plants/all_results.tsv", 
             "../Data/Maaslin2_outs_rare/No rare select/Plants",
             "Plants_only")
```
